### ISSUE TITLE
Error: Cannot GET /

### ISSUE THREAD

**Issue by TomlDev** [Richardn2002/raspivid-broadcaster#1]
Hello,
first thanks for your effort! I was struggling with multiple/late clients on the h264 live player too.

I followed your installation/demo instructions and started with

```
$ node ws+http-server.js
```

When I now try to acccess `http://<raspi-ip>:2050` I get a **404** Error from node:

> Cannot GET /

On Port :8080 I get 

> Upgrade Required

Do you have any idea what I am doing wrong here?

Additional info

Raspberry Pi Zero W
```
$ uname -a
Linux raspberrypi 5.4.79+ #1373 Mon Nov 23 13:18:15 GMT 2020 armv6l GNU/Linux
```

**Comment by Richardn2002** [comment]
Oh sorry, I messed up in the README. You should navigate to `http://<address-of-your-pi>:2050/live.html` instead (look into the `site` folder and you will understand why).
Could you please check if this works for you?

**Comment by TomlDev** [comment]
Works like a charm! 👍🏽
