### ISSUE TITLE
throw error of "spawn raspivid ENOENT"

### ISSUE THREAD

**Issue by tonycph** [Richardn2002/raspivid-broadcaster#2]
Hi. Thanks for your useful information. It is such a great help for us to play around Raspberry Pi robot by 131 and your effrt.  

Below is the error I get after ``` node ws+http-server.js```. Any suggestion?

Paks-MacBook-Air:raspivid-broadcaster pakhocheung$ node ws+http-server.js
(node:41092) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn raspivid ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn raspivid',
  path: 'raspivid',
  spawnargs: [
    '--nopreview', '--width',
    640,           '--height',
    480,           '--framerate',
    20,            '--profile',
    'baseline',    '--timeout',
    0,             '-o',
    '-'
  ]
}

**Comment by Richardn2002** [comment]
The error was thrown when nodejs called `spawn()`, and the only usage of `spawn()` lies in the dependency [raspivid](https://www.npmjs.com/package/raspivid). I'm afraid my codes have little to do with your situation.

However I will not mark this issue as closed at this moment and is willing to help. `ENOENT` mostly happens when the system can not find the executable you want to run. Can you even start `raspivid` from command-line?

If no, then you have to properly configure the system of your pi. If yes, then you may have run into some `PATH` problems (I'm really not sure).

Reading materials:
- The [index.js](https://github.com/binocarlos/raspivid/blob/master/index.js) of the dependency. Really short and straight-forward code. Should not be throwing errors.
- [Stackoverflow](https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js) on nodejs ENOENT when spawning.

(PS: About that [deprecation](https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues/52165509))

**Comment by Richardn2002** [comment]
...wait. From your log you are on your MacBook instead of your Pi. Are you sure you are doing the right thing XD? Of course the server must be run on a Pi with a camera connected.

**Comment by tonycph** [comment]
Hi there. Thanks for the quick reply and apologize for my late response as I was re-wiring all the cables for my PI lol

Yea. You are right. I was messed up with the ws-server.js and ws+http-server.js. Right now, I have the below strucutres and it works prefectly.
PI: ws-server.js
Cloud Server: live.html (changed hostname to PI's hostname using no-ip service)
Client site: access http://CLOUD_SERVER_IP/raspivid-broadcaster/site/live.html

I have one more question about the data transfer size. Let's say there is only 1 client and the data transferred from PI to Cloud Server used 10MB. What if there are 10 clients? Will it be 10MB * 10 clients = 100MB or still 10MB since there is buffer saved by raspivid-broadcaster.js? @Richardn2002

**Comment by tonycph** [comment]
@

**Comment by Richardn2002** [comment]
No, the actual stream data never goes such a route: Pi -> Cloud -> Client. The live.html is just a static webpage that contains the decoder for the stream. It tells clients how to initiate connection with the Pi and how to decode the following stream. Wherever you serve the webpage, the stream data flows from Pi to clients directly. So serving 10MB to 10 clients means 10 * 10 = 100MB from the Pi's web port.

And let me be clear: This repository cares nothing about __efficiency__. The motivation was that in a project of mine I needed streaming with sub-second delay. This approach of transferring raw h.264 data worked well. If you do care about efficiency, bandwidth... etc., you should try conventional approaches like HLS or RTMP protocols. They will first compress the stream before sending (which requires much less bandwidth, but with around 5 seconds' delay).

However, if you are still into my approach and worrying about your Pi's network card blowing up, I actually had written a _relay_.

```js
const WebSocket = require('ws');
class CameraRelay {
    constructor(remoteAddr, localPort) {
        this.wsServer = new WebSocket.Server({port: localPort});
        this.wsServer.on('connection', (socket) => {
            socket.send(this.playerHeader);
            socket.send(this.h264Header, {binary: true});
        });

        this.wsToRemote = new WebSocket('ws://' + remoteAddr);
        this.messageNum = 0;
        this.wsToRemote.on('message', this.incoming.bind(this));
    }

    send(data) {
        this.wsServer.clients.forEach((socket) => {
            socket.send(data, {binary: true});
        });
    }

    incoming(data) {
        switch(this.messageNum) {
            case 0:
                this.playerHeader = data;
                this.messageNum ++;
                break;
            case 1:
                this.h264Header = data;
                this.messageNum ++;
                break;
            default:
                this.send(data);
        }
    }
}
```

Usage: Firstly, start `ws-server.js` on your Pi. Then run a script (allow some time for the Pi to get prepared) on your cloud server consisting of the above script and (for example)

```js
new CameraRelay('192.168.1.3:8080', 8080);
```

Now your server will relay stream data from `192.168.1.3:8080` and serve the data on 8080. Then tell your clients to connect to your server at 8080 in `live.html`. Now no matter how many actual clients are watching the stream, the Pi will only see one 'client', which is your server. The loads for Pi will be lighter.

**Comment by tonycph** [comment]
Thanks for your explanation. 

Let me take a look at ```HLS``` or ```RTMP``` protocols and your ```CameraRelay```. Will need some time to digest it. Thanks again.
